version: '3.7'

services:
    server:
        build:
            context: ./
        command: 'hugo server --bind 0.0.0.0 --config ./hugo-dev.toml --noHTTPCache --watch --baseURL=${CLIENT_HOSTNAME}'
        ports:
            - '1313:1313'
        volumes:
            - '.:/src'
