baseURL = ""
defaultContentLanguage ="en"
theme = "mvp"
enableRobotsTXT = true
disableHugoGeneratorInject = true

uglyURLs = false
cssrelativeurl = false

[params]

[taxonomies] # turn those tax mofos off
tag = ""
category = ""

[languages]
[languages.en]
languageName = "English"
languageCode = "en"
contentDir = "content/en"
weight = 0
title = "Now ship it."
