baseURL = "https://swatches.gallery/"
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "docs"

[params]
siteName = "swatches.gallery"

[markup.goldmark.renderer]
unsafe = true